services:

  web:
    build: .
    container_name: bgiem-document-generator
    ports:
      - "8000:8000"

    env_file:
      - .env

    volumes:
      - ./app:/app/app
      - ./storage:/app/storage

    restart: unless-stopped
