from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_home_page():
    response = client.get("/")
    assert response.status_code == 200
    assert "BGIEM Document Generator" in response.text


def test_documents_list_page():
    response = client.get("/documents")
    assert response.status_code == 200
    assert "Generated Documents" in response.text


def test_reference_number_api():
    response = client.get("/api/reference-number/LOR")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert "reference_number" in data
    assert "LOR" in data["reference_number"]


def test_ai_generation_api():
    payload = {
        "document_type_code": "LOR",
        "student_name": "Test Student",
        "enrollment_no": "0101CS211001",
        "topic": "Higher Education Recommendation",
        "subject": "Recommendation Letter",
        "word_limit": 200
    }
    response = client.post("/api/documents/generate-ai", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert "body" in data
    assert len(data["body"]) > 50


def test_pdf_generation_api():
    payload = {
        "document_type_code": "LOR",
        "reference_no": "BGIEM/CSE/LOR/2026/TEST_SUITE",
        "enrollment_no": "0101CS211001",
        "student_name": "Test Student",
        "topic": "Master of Science Application",
        "subject": "Letter of Recommendation",
        "body": "This is a test body paragraph generated by automated unit test.",
        "word_limit": 200
    }
    response = client.post("/api/documents/generate-pdf", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "ok"
    assert "download_url" in data
    assert "filename" in data
